const colors = {
  dark: {
    text: '#FFFFFF',
    tint: '#0A84FF',
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#1C1C1E',
    cardForeground: '#FFFFFF',
    primary: '#0A84FF',
    primaryForeground: '#FFFFFF',
    secondary: '#2C2C2E',
    secondaryForeground: '#EBEBF5',
    muted: '#2C2C2E',
    mutedForeground: '#8E8E93',
    accent: '#0A84FF',
    accentForeground: '#FFFFFF',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    success: '#30D158',
    warning: '#FF9F0A',
    border: '#38383A',
    input: '#1C1C1E',
    separator: '#38383A',
  },
  light: {
    text: '#000000',
    tint: '#007AFF',
    background: '#F2F2F7',
    foreground: '#000000',
    card: '#FFFFFF',
    cardForeground: '#000000',
    primary: '#007AFF',
    primaryForeground: '#FFFFFF',
    secondary: '#E5E5EA',
    secondaryForeground: '#1C1C1E',
    muted: '#E5E5EA',
    mutedForeground: '#8E8E93',
    accent: '#007AFF',
    accentForeground: '#FFFFFF',
    destructive: '#FF3B30',
    destructiveForeground: '#FFFFFF',
    success: '#34C759',
    warning: '#FF9F0A',
    border: '#C6C6C8',
    input: '#FFFFFF',
    separator: '#C6C6C8',
  },
  radius: 16,
};

export default colors;
